#!/usr/bin/env python3
"""Prints the license notices of the Mesa code in Godot's official Windows
export templates.

Godot's D3D12 renderer links godot-nir-static, a build of Mesa's NIR, SPIR-V
and DXIL compilers. Godot's COPYRIGHT.txt doesn't cover it, so
tools/mesa_notice.sh runs godot-nir-static's own update_mesa.sh (which copies
exactly the Mesa files that get compiled, plus the generated ones) and this
script collects the notice at the top of every one of those files.

Usage: mesa_notice.py <godot-nir-static checkout after update_mesa.sh> <tag>
"""
import collections
import pathlib
import re
import subprocess
import sys

KEYWORDS = re.compile(r"copyright|licen[cs]e|spdx|public domain", re.I)
COMMENT = re.compile(r"/\*.*?\*/|(?:[ \t]*//[^\n]*\n)+", re.S)
SPDX = re.compile(r"SPDX-License-Identifier:\s*([^\n*]+)")

MIT = """Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice (including the next
paragraph) shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE."""


def clean(block):
    """Comment block -> plain text without comment markers."""
    lines = []
    for line in block.splitlines():
        line = re.sub(r"^\s*(/\*+|//+|\*+(?!/))\s?", "", line)
        line = re.sub(r"\s*\*+/\s*$", "", line)
        lines.append(line.rstrip())
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


def notice(path):
    """The first comment block near the top of the file that looks like a notice."""
    head = path.read_text(encoding="utf-8", errors="replace")[:8000]
    for match in COMMENT.finditer(head):
        text = clean(match.group(0))
        if KEYWORDS.search(text):
            return text
    return None


def main():
    nir, tag = pathlib.Path(sys.argv[1]), sys.argv[2]
    tree = nir / "godot-mesa"
    mesa = nir / "mesa"
    commit = subprocess.run(["git", "-C", str(mesa), "rev-parse", "HEAD"],
                            capture_output=True, text=True, check=True).stdout.strip()
    version = (mesa / "VERSION").read_text().strip()

    files = sorted(p for p in tree.rglob("*") if p.is_file() and p.suffix in (".c", ".cpp", ".h"))
    files += sorted((nir / "vulkan").rglob("*.h"))
    groups = collections.defaultdict(list)
    for path in files:
        groups[notice(path)].append(str(path.relative_to(nir)))

    out = [
        f"Mesa {version} (https://mesa3d.org), commit {commit}, as built by",
        f"godot-nir-static {tag} (https://github.com/godotengine/godot-nir-static) into",
        "Godot's official Windows export templates for the D3D12 renderer.",
        "Generated by tools/mesa_notice.sh; do not edit by hand.",
        "",
        "godot-nir-static:",
        "",
        (nir / "LICENSE.md").read_text().strip(),
        "",
        "Mesa's licensing overview (docs/license.rst):",
        "",
        (mesa / "docs" / "license.rst").read_text().strip(),
    ]
    unmarked = groups.pop(None, [])
    for text, paths in sorted(groups.items(), key=lambda kv: (-len(kv[1]), kv[1][0])):
        out += ["", "-" * 79, "Applies to: " + ", ".join(paths), "", text]
    if unmarked:
        out += ["", "-" * 79,
                "No notice in the file itself (covered by the overview above): " + ", ".join(unmarked)]

    spdx = sorted({i.strip() for text in groups for i in SPDX.findall(text)})
    out += ["", "-" * 79, "SPDX license identifiers used above: " + ", ".join(spdx)]
    if any(re.search(r"\bMIT\b", i) for i in spdx):
        out += ["", "Text of the MIT license (SPDX: MIT):", "", MIT]
    vulkan_license = nir / "vulkan" / "LICENSE.txt"
    if vulkan_license.exists():
        out += ["", "-" * 79, "Vulkan headers (vulkan/LICENSE.txt):", "", vulkan_license.read_text().strip()]
    print("\n".join(out))
    print(f"mesa_notice: {len(files)} files, {len(groups)} distinct notices, "
          f"{len(unmarked)} without a notice, SPDX ids: {', '.join(spdx)}", file=sys.stderr)


if __name__ == "__main__":
    main()
